const a = document.querySelector("a");
const input = document.querySelector("input");
console.log(a);
console.log(a.href);
console.log(input.value);
console.log(input.type);
a.href = "https://www.google.com";
console.log((input.value = "Hello"));
console.log((input.type = "password"));
console.log((input.placeholder = "Provide a strong password"));
console.log(input.getAttribute("type"));
console.log(input.setAttribute("placeholder", "Email"));